# Nome do nosso fluxo de trabalho (automação)
name: Atualizar Newsletter Semanal

# Gatilhos: O que faz a automação rodar?
on:
  # 1. Permite rodar manualmente pela aba "Actions" do GitHub
  workflow_dispatch:
  
  # 2. Agenda a execução para toda segunda-feira às 8h da manhã (horário UTC)
  schedule:
    - cron: '0 8 * * 1'

# Tarefas: O que o robô deve fazer?
jobs:
  build-and-deploy:
    # O tipo de máquina virtual que o robô vai usar
    runs-on: ubuntu-latest

    # Os passos que ele vai executar em sequência
    steps:
      # Passo 1: Baixa o código do seu repositório para a máquina virtual
      - name: Checkout do código
        uses: actions/checkout@v3

      # Passo 2: Configura o ambiente Python
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Usaremos Python 3.10

      # Passo 3: Instala as ferramentas (bibliotecas) listadas no requirements.txt
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Passo 4: Executa o seu script Python para gerar o novo newsletter.html
      - name: Gerar novo arquivo da Newsletter
        run: python update_newsletter.py

      # Passo 5: Faz o "commit" - salva o novo arquivo newsletter.html no repositório
      - name: Commit das alterações
        run: |
          git config --global user.name 'Newsletter Bot'
          git config --global user.email 'bot@github.com'
          git add newsletter.html
          # A linha abaixo só faz o commit se houver alguma mudança no arquivo
          git diff --quiet && git diff --staged --quiet || git commit -m "📰 Atualiza newsletter da semana"
          
      # Passo 6: Faz o "push" - envia as alterações para o GitHub, publicando o novo site
      - name: Push das alterações
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
